version: '2'

services:
  app:
    image: python
    ports:
      - 8001:8000
    working_dir: /app
    volumes:
      - .:/app:ro
    command: 'python3 -m http.server 8000'

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    depends_on: [app]
    ports:
      - 8002:80
